### ISSUE TITLE
Путь до SmartMetersConfig.properties файла передается в виде аргумента

### ISSUE THREAD

**Issue by KMax** [semiotproject/simulator-heat-meters#3]
Сейчас SmartMetersConfig.properties "зашит" в .jar файл, т.е. чтобы его отредактировать придется перекомпилировать всю программу. Поэтому путь до этого файла должен передаваться программе в виде аргумента.

**Comment by soylent-grin** [comment]
При запуске приложения первым аргументом передается путь к конфигурационному файлу; если запуск без аргументов - берутся дефолтные настройки.

**Comment by KMax** [comment]
Можно было бы продолжить использовать Owner для конфигурации :( Тут описано как подгружать из файла -> http://owner.aeonbits.org/docs/importing-properties/
