### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by KMax** [semiotproject/simulator-heat-meters#5]
- the container should be based on Ubuntu and configured as it described in #4. 
- conf file for the simulator should be downloaded and used if the `SIMULATOR_CONF` environment variable provided with the link.

**Comment by soylent-grin** [comment]
According to [this](http://stackoverflow.com/a/24331638), changing ulimits is not supported inside of a container, so we need to change them manually on the host machine and restart docker service.

**Comment by KMax** [comment]
It's sad to hear, but the workaround is fine for me. Thanks!

**Comment by KMax** [comment]
Let's switch to Java 8 for the container. [Here](https://github.com/ailabitmo/DAAFSE/blob/master/dockerfiles/alert-service/Dockerfile) is an example how to install Java 8 on Ubuntu.
